### PR TITLE
Output Bootstraps for assignTaxonomy

### PR DESCRIPTION
**Pull request by gblanchard4**
This is the code I worked up for #124 

I did not modify the C function because the `assignment` variable returned by it already contained all the taxa assignments and bootstrap values before minBoot filtering. 

I added the `outputBootstraps` to handle the logic of what to return. I am new to R and wasn't quite sure the best way to return two matrices, is returning a list of them the way you want it?

I return all the bootstrap values even if the taxa gets trimmed that way you can see if it was borderline passing or not. 
```
> at90 <- assignTaxonomy(seqtab.nochim, "rdp_train_set_14.fa.gz", minBoot=90, outputBootstraps=TRUE)
> at90[[1]][213,]
     Kingdom       Phylum        Class        Order       Family        Genus 
  "Bacteria" "Firmicutes"           NA           NA           NA           NA 
> at90[[2]][213,]
Kingdom  Phylum   Class   Order  Family   Genus 
    100      90      73      73       8       8 
> 
```

I would be happy to make any fixes needed!

### CODE REVIEW

**Comment by gblanchard4** [comment]
Thanks for the feedback!

I think a named list is a great idea and reordering the flags make sense. I will take care of those shortly. 

When I originally wrote the loop I set minBoot=0 if outputBootstraps==TRUE. I wasn't sure what the best practice would be, so I left minBoot's value alone to avoid unintended consequences. 

Do you think the docstring is descriptive enough? Should I include an example case too?

**Comment by benjjneb** [comment]
I think this behavior is fine (leaving minBoot as is) since the other behavior is easy to get if desired (set minBoot=0).

The docstring is ok, I would be slightly more descriptive in the description of the parameter though, and mention the changed return value there as well.

**Comment by benjjneb** [comment]
LGTM, but because this pull request introduces a new function flag it won't make the 1.2 release which is already API frozen.

I'll merge this in once the 1.2 release is finalized (a week or so).

**Comment by gblanchard4** [comment]
Great! :smile:

**Pull request merged**
